t = Tournament.create(name:"turniej", max_round_number: 3)
Player.create(name:"Jan", surname: "Kowalski", tournament_id: t.id)
Player.create(name:"Meczysław", surname: "Nowak", tournament_id: t.id)
Player.create(name:"Gniewomir", surname: "Aaa", tournament_id: t.id)
Player.create(name:"Ziemowit", surname: "Kowalski", tournament_id: t.id)
Player.create(name:"Marian", surname: "Kowalski", tournament_id: t.id)
Player.create(name:"Piotr2", surname: "Nowak", tournament_id: t.id)
Player.create(name:"Piotr", surname: "Kowalski", tournament_id: t.id)